CREATE database NETLFIX_DATA;
-- CREATING TABLES 
CREATE TABLE Movie
(
TITLE VARCHAR(50),
WRITER VARCHAR(50),
DURATION VARCHAR(50),
RATING INT NOT NULL
);

CREATE TABLE tv_show
(
TITLE VARCHAR(50),
WRITER VARCHAR(50),
DURATION VARCHAR(50),
RATING INT NOT NULL
);

CREATE TABLE Series	
(
TITLE VARCHAR(50),
WRITER VARCHAR(50),
DURATION VARCHAR(50),
RATING INT NOT NULL
);

CREATE TABLE Prices 
( 
MOVIES VARCHAR(50),
TV_SHOWS VARCHAR(50),
SERIES VARCHAR(50)
);
-- assigning values

INSERT INTO Movie  (TITLE,WRITER,DURATION,RATING) VALUES ('PYAAR','ARU','120 MIN' ,5);
INSERT INTO Movie  (TITLE,WRITER,DURATION,RATING) VALUES ('DIL','ASHU','150 MIN' ,3);
INSERT INTO Movie  (TITLE,WRITER,DURATION,RATING) VALUES ('BHAROSA','ARIDHI','130 MIN' ,4);
INSERT INTO Movie  (TITLE,WRITER,DURATION,RATING) VALUES ('ISHQ','ABHI','190 MIN' ,5);
INSERT INTO Movie  (TITLE,WRITER,DURATION,RATING) VALUES ('PHOOL','ARU','160 MIN',4);


INSERT INTO  tv_show  (TITLE,WRITER,DURATION,RATING) VALUES ('SAAS','ARPITA','30 MIN ' ,5);
INSERT INTO  tv_show (TITLE,WRITER,DURATION,RATING) VALUES ('BAHU','ANJALI','40 MIN ' ,4);
INSERT INTO  tv_show (TITLE,WRITER,DURATION,RATING) VALUES ('PYAAR DIL','ARI','45 MIN' ,3);
INSERT INTO  tv_show (TITLE,WRITER,DURATION,RATING) VALUES ('GHAR','ARU','30 MIN' ,2);
INSERT INTO  tv_show (TITLE,WRITER,DURATION,RATING) VALUES ('SAATH','ADI','35MI N' ,5);

INSERT INTO Series	  (TITLE,WRITER,DURATION,RATING) VALUES ('LOVE','ARPI','5 EPISODES' ,5);
INSERT INTO Series	 (TITLE,WRITER,DURATION,RATING) VALUES ('HEART','ARTI','4 EPISODES' ,4);
INSERT INTO Series	 (TITLE,WRITER,DURATION,RATING) VALUES ('BOOKS','ANUREET','6 EPISODES' ,3);
INSERT INTO Series	 (TITLE,WRITER,DURATION,RATING) VALUES ('FRIENDS','ARSHITA','8 EPISODES' ,4);
INSERT INTO Series	 (TITLE,WRITER,DURATION,RATING) VALUES ('FAMILY','ARU','4 EPISODES' ,5);


 INSERT INTO PRICES	 (MOVIES,TV_SHOWS,SERIES) VALUES ('300 RS','150 RS','500 RS');
 
 SELECT*
 FROM Movie
 ;
 
 SELECT*
 FROM Prices
 ;
 
  SELECT*
 FROM tv_show
 ;
 
  SELECT*
 FROM Series
 ;
 
 -- QUERIES
 
-- how many movies are there of same title
 SELECT title,count(*)
 from Movie
 group by title;
 
 -- WRITERS ONLY 
 SELECT WRITER 
 FROM Movie
 GROUP BY WRITER
 ;
 
 -- RATING
SELECT*
FROM Series
where RATING>=4;

-- SHOW DETAILS OF A TV SHOW 'SAATH'
SELECT*
FROM tv_show
where title like '%SAATH%';

-- TO FIND LONGEST MOVIE
SELECT *
FROM Movie
order by duration DESC
LIMIT 1;

-- AVG RATING OF TV SHOWS
SELECT AVG(rating) AS avg_rating
FROM tv_show;

-- UNION OF ALL 
SELECT title, writer, rating FROM movie
UNION
SELECT title, writer, rating FROM tv_show
UNION
SELECT title, writer, rating FROM series
;

-- total series
SELECT COUNT(*) AS total_series
FROM Series;

-- highest rated movie
SELECT *
FROM movie
ORDER BY rating DESC
LIMIT 1;

-- convert varchar to int(number)
SELECT
    REPLACE(movies, ' RS', '') AS movie_price,
    REPLACE(tv_shows, ' RS', '') AS tv_price,
    REPLACE(series, ' RS', '') AS series_price
FROM prices;




 
 
 
 
 
 
 
 
 
 
 
 
